name: generate-changelog
description: Generate and commit the CHANGELOG, and update the body of the Pull Request.
inputs:
  get-version:
    description: 'Script for extracting current version'
    default: |
      node --print 'require("./package.json").version'
    required: true
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/release-meta
      id: release-meta
      with:
        get-version: ${{ inputs.get-version }}

    - name: Update PR body
      uses: actions/github-script@v4
      with:
        script: |
          github.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            title: `Release ${process.env.RELEASE_TAG}`,
            body: process.env.RELEASE_NOTE,
          })
      env:
        RELEASE_NOTE: ${{ steps.release-meta.outputs.note }}
        RELEASE_TAG: ${{ steps.release-meta.outputs.tag }}

    - name: Setup git
      shell: bash
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Update CHANGELOG.md
      shell: bash
      run: |
        mkdir -p tmp
        echo "${RELEASE_NOTE}" > tmp/CHANGELOG.head.md
        git show ${{ github.event.pull_request.base.sha }}:./CHANGELOG.md > tmp/CHANGELOG.base.md
        cat -s tmp/CHANGELOG.head.md tmp/CHANGELOG.base.md > CHANGELOG.md
        git checkout ${{ github.event.pull_request.head.ref }}
        git add CHANGELOG.md
        git commit -m "Update CHANGELOG for ${RELEASE_TAG}"
        git push origin HEAD:${{ github.event.pull_request.head.ref }}
      env:
        RELEASE_TAG: ${{ steps.release-meta.outputs.tag }}
        RELEASE_NOTE: ${{ steps.release-meta.outputs.note }}
