// Code generated by graphql-codegen. DO NOT EDIT.
import * as Types from "../../__generated__/graphqlTypes";

import { TypedDocumentNode as DocumentNode } from "@graphql-typed-document-node/core";
import gql from "graphql-tag";
export type PostSummaryFragment = {
  readonly __typename?: "Post";
  readonly title: string;
  readonly body: string;
  readonly user: {
    readonly __typename?: "User";
    readonly username: string;
    readonly thumbnailUrl?: Types.Maybe<string>;
  };
};

export type GetPostSummaryQueryVariables = Types.Exact<{
  postId: Types.Scalars["String"];
}>;

export type GetPostSummaryQuery = {
  readonly __typename?: "Query";
  readonly postById: {
    readonly __typename?: "Post";
    readonly id: string;
    readonly title: string;
    readonly body: string;
    readonly user: {
      readonly __typename?: "User";
      readonly username: string;
      readonly thumbnailUrl?: Types.Maybe<string>;
    };
  };
};

export const PostSummaryFragmentDoc = {
  kind: "Document",
  definitions: [
    {
      kind: "FragmentDefinition",
      name: { kind: "Name", value: "PostSummary" },
      typeCondition: { kind: "NamedType", name: { kind: "Name", value: "Post" } },
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          { kind: "Field", name: { kind: "Name", value: "title" } },
          { kind: "Field", name: { kind: "Name", value: "body" } },
          {
            kind: "Field",
            alias: { kind: "Name", value: "user" },
            name: { kind: "Name", value: "author" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "username" } },
                {
                  kind: "Field",
                  alias: { kind: "Name", value: "thumbnailUrl" },
                  name: { kind: "Name", value: "avatarUrl" },
                },
              ],
            },
          },
        ],
      },
    },
  ],
} as unknown as DocumentNode<PostSummaryFragment, unknown>;
export const GetPostSummaryDocument = {
  kind: "Document",
  definitions: [
    {
      kind: "OperationDefinition",
      operation: "query",
      name: { kind: "Name", value: "GetPostSummary" },
      variableDefinitions: [
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "postId" } },
          type: { kind: "NonNullType", type: { kind: "NamedType", name: { kind: "Name", value: "String" } } },
        },
      ],
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          {
            kind: "Field",
            name: { kind: "Name", value: "postById" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "postId" },
                value: { kind: "Variable", name: { kind: "Name", value: "postId" } },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "id" } },
                { kind: "FragmentSpread", name: { kind: "Name", value: "PostSummary" } },
              ],
            },
          },
        ],
      },
    },
    ...PostSummaryFragmentDoc.definitions,
  ],
} as unknown as DocumentNode<GetPostSummaryQuery, GetPostSummaryQueryVariables>;
export const PostSummary = gql`
  fragment PostSummary on Post {
    title
    body
    user: author {
      username
      thumbnailUrl: avatarUrl
    }
  }
`;
export const GetPostSummary = gql`
  query GetPostSummary($postId: String!) {
    postById(postId: $postId) {
      id
      ...PostSummary
    }
  }
  ${PostSummary}
`;
