// Code generated by graphql-codegen. DO NOT EDIT.
import * as Types from "../../__generated__/graphqlTypes";

import { TypedDocumentNode as DocumentNode } from "@graphql-typed-document-node/core";
export type PostHeaderUserFragment = {
  readonly __typename?: "User";
  readonly username: string;
  readonly avatarUrl?: Types.Maybe<string>;
};

export type PostHeaderFragment = {
  readonly __typename?: "Post";
  readonly title: string;
  readonly author: {
    readonly __typename?: "User";
    readonly username: string;
    readonly avatarUrl?: Types.Maybe<string>;
  };
};

export type GetPostHeaderQueryVariables = Types.Exact<{
  postId: Types.Scalars["String"];
}>;

export type GetPostHeaderQuery = {
  readonly __typename?: "Query";
  readonly postById: {
    readonly __typename?: "Post";
    readonly id: string;
    readonly title: string;
    readonly author: {
      readonly __typename?: "User";
      readonly id: string;
      readonly username: string;
      readonly avatarUrl?: Types.Maybe<string>;
    };
  };
};

export const PostHeaderUserFragmentDoc = {
  kind: "Document",
  definitions: [
    {
      kind: "FragmentDefinition",
      name: { kind: "Name", value: "PostHeaderUser" },
      typeCondition: { kind: "NamedType", name: { kind: "Name", value: "User" } },
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          { kind: "Field", name: { kind: "Name", value: "username" } },
          { kind: "Field", name: { kind: "Name", value: "avatarUrl" } },
        ],
      },
    },
  ],
} as unknown as DocumentNode<PostHeaderUserFragment, unknown>;
export const PostHeaderFragmentDoc = {
  kind: "Document",
  definitions: [
    {
      kind: "FragmentDefinition",
      name: { kind: "Name", value: "PostHeader" },
      typeCondition: { kind: "NamedType", name: { kind: "Name", value: "Post" } },
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          { kind: "Field", name: { kind: "Name", value: "title" } },
          {
            kind: "Field",
            name: { kind: "Name", value: "author" },
            selectionSet: {
              kind: "SelectionSet",
              selections: [{ kind: "FragmentSpread", name: { kind: "Name", value: "PostHeaderUser" } }],
            },
          },
        ],
      },
    },
    ...PostHeaderUserFragmentDoc.definitions,
  ],
} as unknown as DocumentNode<PostHeaderFragment, unknown>;
export const GetPostHeaderDocument = {
  kind: "Document",
  definitions: [
    {
      kind: "OperationDefinition",
      operation: "query",
      name: { kind: "Name", value: "GetPostHeader" },
      variableDefinitions: [
        {
          kind: "VariableDefinition",
          variable: { kind: "Variable", name: { kind: "Name", value: "postId" } },
          type: { kind: "NonNullType", type: { kind: "NamedType", name: { kind: "Name", value: "String" } } },
        },
      ],
      selectionSet: {
        kind: "SelectionSet",
        selections: [
          {
            kind: "Field",
            name: { kind: "Name", value: "postById" },
            arguments: [
              {
                kind: "Argument",
                name: { kind: "Name", value: "postId" },
                value: { kind: "Variable", name: { kind: "Name", value: "postId" } },
              },
            ],
            selectionSet: {
              kind: "SelectionSet",
              selections: [
                { kind: "Field", name: { kind: "Name", value: "id" } },
                {
                  kind: "Field",
                  name: { kind: "Name", value: "author" },
                  selectionSet: {
                    kind: "SelectionSet",
                    selections: [{ kind: "Field", name: { kind: "Name", value: "id" } }],
                  },
                },
                { kind: "FragmentSpread", name: { kind: "Name", value: "PostHeader" } },
              ],
            },
          },
        ],
      },
    },
    ...PostHeaderFragmentDoc.definitions,
  ],
} as unknown as DocumentNode<GetPostHeaderQuery, GetPostHeaderQueryVariables>;
