name: Release PR

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  release-note:
    if: startswith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: yarn --frozen-lockfile

    - uses: ./.github/actions/generate-changelog
